### ISSUE TITLE
Access metadata using optics

### ISSUE THREAD

**Issue by mijicd** [scalaz/scalaz-distributed#4]
Library design assumes usage of `Lens` and `Prism` for metadata access (see #2). Since one of the goals of `scalaz-distributed` is to minimize the number of external dependencies, it is not an option to use `Monocle`. 

Provide an implementation of `Lens` and `Prism`. In case additional typeclasses are introduced, briefly explain their purpose in the context of `scalaz-distributed`.

**Comment by mijicd** [comment]
cc @pshemass

**Comment by jdegoes** [comment]
There are other reasons for not using `Lens` / `Prism`. These are just pairs of functions in Monocle and other libraries, but will be reified paths in the implementation of Distributed.

We'll have a List like data structure that holds the path to the value being modified. So they won't be functions at all, but data structures.

**Comment by pshemass** [comment]
In my initial PR I was trying to achieve the same idea (path to value) by PathElem algebra. Let me know what are your thoughts about this? 

```
sealed trait PathElem[A, B]
  object PathElem {
    case class Key[K, V](v: K) extends PathElem[Map[K, V], V]
    case class Elements[A]() extends PathElem[Set[A], A]
    case class Composed[A, B, C](l: PathElem[A, B], r: PathElem[B, C]) extends PathElem[A, C]
  }

implicit class LensSyntax[A: Type, B: Type](self: PathElem[A, B]) {
    def >>> [C: Type](that: PathElem[B, C]): PathElem[A, C] = PathElem.Composed(self, that)
  }

  def key[K: Type, V: Type](k: K): PathElem[Map[K, V], V] = PathElem.Key[K, V](k)

  def elements[V: Type]: PathElem[Set[V], V] = PathElem.Elements[V]()

```

**Comment by jdegoes** [comment]
Yes, that's along the lines of what we'll need, except we need to reify type information (e.g. the `: Type` part of it), and we may choose to discard it for the concrete types in the module (e.g. `PathElem` in the above would be a concrete implementation detail in the module implementation, not visible to a user of the library).

**Comment by pshemass** [comment]
ok will add more specific type for PathElems.

How would you hide this? 
I was thinking about 
```
  type Path[A, B] = PathElem[A, B]

  sealed trait PathElem[A, B]
  private object PathElem {
    case class Key[K: Type, V: Type](v: K) extends PathElem[Map[K, V], V]
    case class Elements[A: Type]() extends PathElem[Set[A], A]
    case class Composed[A: Type, B: Type, C: Type](l: PathElem[A, B], r: PathElem[B, C]) extends PathElem[A, C]
  }

  implicit class PathSyntax[A: Type, B: Type](self: Path[A, B]) {
    def >>> [C: Type](that: Path[B, C]): Path[A, C] = PathElem.Composed(self, that)
  }

  def key[K: Type, V: Type](k: K): Path[Map[K, V], V] = PathElem.Key[K, V](k)
```

in this case there will be still leak PathElem. Do you think that is acceptable?


usage might look as follow:
```
 def run(DM: DistributedModule, m: Member) = {
    import DM._
    for {
      p <- startup(m, Set())
      m <- p.access[Map[String, Map[Int, String]]](MetadataID("users"))
      _ <- m.set(key[String, Map[Int, String]]("alice") >>> key[Int, String](1) , "bob")
    } yield ()
  }
```
